# Generated by Django 3.2.12 on 2022-04-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, choices=[('Cybersecurity and IT reviews', 'Cybersecurity and IT reviews'), ('IT Software and Solutions', 'IT Software and Solutions'), ('IT Project consulting', 'IT Project consulting')], max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Service & Product Category',
            },
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name_plural': 'Service & Products'},
        ),
        migrations.AlterField(
            model_name='offers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='landing.category'),
        ),
        migrations.DeleteModel(
            name='ALL_Category',
        ),
    ]
