# Generated by Django 3.2.12 on 2022-04-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20220410_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='group',
            new_name='Group',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='types',
        ),
        migrations.AddField(
            model_name='offers',
            name='Name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Service/Product Name'),
        ),
        migrations.AddField(
            model_name='offers',
            name='Types',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Solution', 'Solution')], max_length=255),
        ),
    ]
