# Generated by Django 3.2.12 on 2022-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20220410_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='Group',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='offers',
            name='Types',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Solution', 'Solution')], max_length=255, verbose_name='Service/Product Type'),
        ),
    ]
