# Generated by Django 3.2.12 on 2022-04-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20220410_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=700, verbose_name='Title')),
                ('Description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Case Study',
            },
        ),
    ]
