# Generated by Django 3.2.12 on 2022-05-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20220511_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='Content',
        ),
    ]
