# Generated by Django 4.0.4 on 2022-10-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20220511_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'verbose_name_plural': 'Culture'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name_plural': 'Mission'},
        ),
    ]
